# -*- coding: utf-8 -*-
"""NLP_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSOS1lX9yEfjPGZGpZhEFgtMMjqz4ENO

# NLP-03 — Regular Expressions for Information Extraction and Validation
"""

import re
import pandas as pd

text = """
Contact us at support@example.com or admin@university.edu.
Visit https://www.example.com, http://nlp.org or https://github.com.
Phone numbers are +91-9876543210, +91 8765432109, and 020-1234567.
Important dates are 15/08/2026, 01-01-2027 and 25/12/2026.
Follow #ArtificialIntelligence, #MachineLearning, #NLP and #DeepLearning.
"""

# Email Pattern
email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'

# URL Pattern
url_pattern = r'https?://[^\s]+'

# Phone Number Pattern
phone_pattern = r'(?:\+91[- ]?)?[0-9]{10}|[0-9]{3}-[0-9]{7}'

# Date Pattern
date_pattern = r'\b\d{1,2}[-/]\d{1,2}[-/]\d{4}\b'

# Hashtag Pattern
hashtag_pattern = r'#\w+'

emails = re.findall(email_pattern, text)
urls = re.findall(url_pattern, text)
phones = re.findall(phone_pattern, text)
dates = re.findall(date_pattern, text)
hashtags = re.findall(hashtag_pattern, text)

print("Emails:", emails)
print("URLs:", urls)
print("Phone Numbers:", phones)
print("Dates:", dates)
print("Hashtags:", hashtags)

max_len = max(
    len(emails),
    len(urls),
    len(phones),
    len(dates),
    len(hashtags)
)

emails += [''] * (max_len - len(emails))
urls += [''] * (max_len - len(urls))
phones += [''] * (max_len - len(phones))
dates += [''] * (max_len - len(dates))
hashtags += [''] * (max_len - len(hashtags))

df = pd.DataFrame({
    'Emails': emails,
    'URLs': urls,
    'Phone Numbers': phones,
    'Dates': dates,
    'Hashtags': hashtags
})

df

def validate_email(email):
    pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    return bool(re.match(pattern, email))

def validate_url(url):
    pattern = r'^https?://[^\s]+$'
    return bool(re.match(pattern, url))

def validate_phone(phone):
    pattern = r'^(?:\+91[- ]?)?[0-9]{10}|[0-9]{3}-[0-9]{7}$'
    return bool(re.match(pattern, phone))

def validate_date(date):
    pattern = r'^\d{1,2}[-/]\d{1,2}[-/]\d{4}$'
    return bool(re.match(pattern, date))

print("Email Validation")

for email in emails:
    if email:
        print(email, "->", validate_email(email))

print("\nURL Validation")

for url in urls:
    if url:
        print(url, "->", validate_url(url))

print("\nPhone Number Validation")

for phone in phones:
    if phone:
        print(phone, "->", validate_phone(phone))

print("\nDate Validation")

for date in dates:
    if date:
        print(date, "->", validate_date(date))