# -*- coding: utf-8 -*-
"""NLP_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSvGE1v5BfgtzZCk4RMYzEPg-EghvOpG

# NLP-01 — NLP Libraries and Basic Text Processing

## 1. Install and Verify NLTK
"""

!pip install nltk

import nltk
print(nltk.__version__)

nltk.download('punkt')

import nltk
nltk.download('punkt_tab')

"""## 2. Word Tokenization using NLTK"""

from nltk.tokenize import word_tokenize

text = "Hello, how are you?"
print(word_tokenize(text))

"""## 3. Install and Load spaCy"""

!pip install spacy

import sys
!{sys.executable} -m spacy download en_core_web_sm

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Hello, I am learning spaCy.")
print([token.text for token in doc])

"""## 4. Install Gensim and Create a Bag-of-Words Corpus"""

!pip install gensim

from gensim import corpora

# 1. Sample tokenized documents
documents = [
    ["natural", "language", "processing"],
    ["language", "models", "word", "embeddings"]
]

# 2. Build dictionary
dictionary = corpora.Dictionary(documents)

# 3. Convert documents to Bag-of-Words vectors (the corpus)
corpus = [dictionary.doc2bow(doc) for doc in documents]

print(corpus)

corpus = [[(0, 1), (1, 1), (2, 1)], [(0, 1), (3, 1), (4, 1), (5, 1)]]

# Print actual words for the first document:
doc_0 = corpus[0]
decoded_doc = [(dictionary[id], count) for id, count in doc_0]

print(decoded_doc)

"""## 5. Install PyTorch"""

!pip install torch

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

"""## 6. Install Hugging Face Transformers and Datasets"""

!pip install transformers huggingface_hub datasets

"""## 7. Sentiment Analysis using Hugging Face Pipeline"""

from transformers import pipeline

# Load a quick sentiment analysis pipeline
classifier = pipeline("sentiment-analysis")
result = classifier("Installing Hugging Face is so easy.")

print(result)

from transformers import pipeline

classifier = pipeline("sentiment-analysis")
result = classifier("I love Natural Language Processing")
print(result)