# -*- coding: utf-8 -*-
"""NLP_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWyZm_S7-ws8nJwtIaeIjaZle9rJEBdm

# NLP-02 — Text Preprocessing
"""

import nltk

nltk.download('omw-1.4')

nltk.download('wordnet')

import re
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

documents = [
    "Natural language processing is transforming Artificial Intelligence.",
    "Machine learning model require clean and normalized text data.",
    "Tokenization, stemming, and lemmatization are important NLP preprocessing step."
]

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Normalization
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenization
    tokens = word_tokenize(text)

    # Stop-word removal
    filtered_tokens = [word for word in tokens if word not in stop_words]

    # Stemming
    stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]

    # Lemmatization
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

    return {
        'Original_Text': text,
        'Tokens': tokens,
        'After_Stopword_Removal': filtered_tokens,
        'Stemmed': stemmed_tokens,
        'Lemmatized': lemmatized_tokens
    }

nltk.download('punkt_tab')
result = [preprocess_text(doc) for doc in documents]

df = pd.DataFrame(result)
df